#### plots in R

data <- data.frame(a = runif(25), b = rnorm(25), c = rexp(25))
attach(data)

### line plot
r <- runif(300) + 3
plot(r, t="l",main="main", xlab="xlab", ylab="ylab", ylim=c(-.5,4))
grid()  			
# with additional lines:
lines(x=abs(r)-2, col="lightblue")
lines(x=abs(r)-3, col="blue", t="h", pch=1)

abline(h=.5, col="red")
abline(v=12, col="green")

### line plot with different line types (lty) and colors (col)
plot(b, t="o",lty=3, col=2)


### scatter plot with different markers (pch)
plot(c, pch=2, col="lightgreen")


### plot matrix with each column one line
matplot(data, t="l")


### save plot to pdf with autogenerated dated name:
currentDateTime <- format(Sys.time(),"%Y-%m-%d_%H-%M-%S")
fileName <- paste("plot_", currentDateTime,".pdf", sep="")
pdf(file=fileName)
plot(rnorm(10,2,4), t="l", col="slateblue")
dev.off()


### multiple plots in 1 grid with one legend:
# par(xpd=TRUE) to place legend in the margins without trimming it
op <- par(mfrow=c(1,3), xpd=TRUE)
plot(a, t="h", col="magenta")
plot(b, t="o", col="blue", pch=0)
legend("bottom",inset=c(-3,1.05),names(data),pch=c(NA,0,3), lty=c(1,1,NA), 
       horiz=TRUE, col=c("magenta","blue","green"))
plot(c, pch = 3, col="green")
par(op)



### plot multiple y-axis:

time<-seq(7000,3400,-200)
pop<-c(200,400,450,500,300,100,400,700,830,1200,400,350,200,700,370,800,200,100,120)
grp<-c(2,5,8,3,2,2,4,7,9,4,4,2,2,7,5,12,5,4,4)
med<-c(1.2,1.3,1.2,0.9,2.1,1.4,2.9,3.4,2.1,1.1,1.2,1.5,1.2,0.9,0.5,3.3,2.2,1.1,1.2)


# Define Margins. The trick is to use give as much space possible on the left 
# margin (second value)
par(mar=c(5, 12, 4, 4) + 0.1)

# Plot the first time series. Notice that you don't have to draw the axis nor 
# the labels
plot(time, pop, axes=F, ylim=c(0,max(pop)), xlab="", ylab="",type="l",
     col="black", main="",xlim=c(7000,3400))
points(time,pop,pch=20,col="black")
axis(2, ylim=c(0,max(pop)),col="black",lwd=2)
mtext(2,text="Population",line=2)

# Plot the second time series. The command par(new=T) is handy here. If you just 
# need to plot two timeseries, you could also use the right vertical axis as
# well. In that case you have to substitute "2" with "4" in the functions axis() 
# and mtext(). Notice that in both functions lines is increased so that the new 
# axis and its label is placed to the left of the first one. You don't need to 
# increase the value if you use the right vertical axis.
par(new=T)
plot(time, med, axes=F, ylim=c(0,max(med)), xlab="", ylab="", 
type="l",lty=2, main="",xlim=c(7000,3400),lwd=2)
axis(2, ylim=c(0,max(med)),lwd=2,line=3.5)
points(time, med,pch=20)
mtext(2,text="Median Group Size",line=5.5)

# Plot the third time series. Again the line parameter are both further 
# increased.
par(new=T)
plot(time, grp, axes=F, ylim=c(0,max(grp)), xlab="", ylab="", 
type="l",lty=3, main="",xlim=c(7000,3400),lwd=2)
axis(2, ylim=c(0,max(grp)),lwd=2,line=7)

points(time, grp,pch=20)
mtext(2,text="Number of Groups",line=9)

# We can now draw the X-axis, which is of course shared by all the three 
# time-series.
axis(1,pretty(range(time),10))
mtext("cal BP",side=1,col="black",line=2)

#And then plot the legend.
legend(x=7000,y=12,legend=c("Population","Median Group Size","Number of Groups"),
       lty=c(1,2,3))




### bar plot:
barplot(a, col=rainbow(length(a)))
barplot(as.matrix(data), col=heat.colors(length(a)))
barplot(as.matrix(data), beside=T, col=terrain.colors(length(a)))

install.packages('ggplot2')
require('ggplot2')
?geom_bar

ggplot(diamonds, aes(clarity)) + geom_bar() + facet_wrap(~ cut)


### histogram with density overlay:
hist(mtcars$mpg,xlab="Miles per Gallon", prob=T)
lines(density(mtcars$mpg), col="blue")


### histogram/density per group:
require("lattice")

histogram(~mtcars$mpg | as.factor(mtcars$cyl), auto.key=T)

histogram( ~ height | voice.part, data = singer,
           xlab = "Height (inches)", type = "density",
           panel = function(x, ...) {
             panel.histogram(x, ...)
             panel.mathdensity(dmath = dnorm, col = "black",
                               args = list(mean=mean(x),sd=sd(x)))
           } )

densityplot( ~ height | voice.part, data = singer, layout = c(2, 4),  
             xlab = "Height (inches)", bw = 5)


### cdf & boypol comparison
x01 <- seq(0,1,by=.01)
beta <- dbeta(x01,2,5)
plot(x01, beta, t='l', col='blue', xlim=c(0,1.5))
boxplot(beta,add=T,at=1.2)


### automatic colors for lots of lines:
#names of colors are saved in colors()
colors()
length(colors())

ncol <- 5
nrow <- 100
scores <- matrix(rnorm(ncol*nrow,2,4),ncol=ncol)

# using colorRampPalette:
col <- colorRampPalette(c("tan1","tan4"))(ncol)
matplot(scores, t="l", lwd=2, col=col, lty=1)

# using palette:
palette(gray(seq(0,.9,len=ncol))) # gray scales; print old palette
matplot(scores, t="l", lwd=2, lty=1)
palette("default") # reset colors back to default


# color matching legend
a <- sample(1:100)
cuts <- levels(cut(a,breaks = 10))
cuts <- gsub(","," - ",cuts)
cuts <- gsub("\\(","[",cuts)
rbPal <- colorRampPalette(c('red','blue'))
b <- rbPal(10)[as.numeric(cut(a,breaks = 10))]
plot(a,col=b,pch=16)
legend("top",cuts,col=rbPal(10),pch=16)


### maps



### Add boxplots to a scatterplot
op <- par(fig=c(0,0.8,0,0.8))
plot(mtcars$wt, mtcars$mpg, xlab="Miles Per Gallon",
     ylab="Car Weight")
par(fig=c(0,0.8,0.55,1), new=TRUE)
boxplot(mtcars$wt, horizontal=TRUE, axes=FALSE)
par(fig=c(0.65,1,0,0.8),new=TRUE)
boxplot(mtcars$mpg, axes=FALSE)
mtext("Enhanced Scatterplot", side=3, outer=TRUE, line=-3)
par(op)



### comparison density with boxplot
n <- 550
toright <- abs(rnorm(n,mean=15,sd=11) + rnorm(n,mean=10,sd=40))
dright <- density(toright, from=min(toright), to=max(toright))

toleft <- c(sample(seq(22,28,by=.4), 150, replace=T),
            sample(seq(25,27.5,by=.1), 500, replace=T),
            sample(seq(25.5,27.8,by=.02), 300, replace=T),
            sample(seq(26.5,27.8,by=.001), 500, replace=T))
dleft <- density(toleft, from=min(toleft), to=max(toleft))

# fig= parameter is a numerical vector of the form c(x1, x2, y1, y2)
op <- par(fig=c(0,1,0.4,1))
plot(dright$x, dright$y, xlab='', ylab='Density', t='l',
     main='Density & Boxplot: skewed to the right')
#plot mean in density:
m <- seq(min(dright$y),max(dright$y),length=10)
points(rep(mean(toright), length(m)), m, pch=3, col='blue')
#add boxplot:
par(fig=c(0,1,0,0.6), new=T)
boxplot(toright, horizontal=T, ylab='Boxplot', xlab='Minutes')
#plot mean in boxplot:
mm <- seq(0.5,1.5,length=10)
points(rep(mean(toright), length(mm)), mm, pch=3, col='blue')
par(op)

# fig= parameter is a numerical vector of the form c(x1, x2, y1, y2)
op <- par(fig=c(0,1,0.4,1))
plot(dleft$x, dleft$y, xlab='', ylab='Density', t='l',
     main='Density & Boxplot: skewed to the left')
#plot mean in density:
m <- seq(min(dleft$y),max(dleft$y),length=10)
points(rep(mean(toleft), length(m)), m, pch=3, col='blue')
#add boxplot:
par(fig=c(0,1,0,0.6), new=T)
boxplot(toleft, horizontal=T, ylab='Boxplot', xlab='Minutes')
#plot mean in boxplot:
mm <- seq(0.5,1.5,length=10)
points(rep(mean(toleft), length(mm)), mm, pch=3, col='blue')
par(op)



### plot within plot: (like zoom into)
library('MASS')
data(Animals)
# fig= parameter is a numerical vector of the form c(x1, x2, y1, y2)
op <- par(fig=c(0,1,0,1), cex=1.3)
plot(Animals, main='Body weight vs. brain weight for animals',
     xlab='body weight in kg', ylab='brain weight in g')
innerx1 <- 0; innerx2 <- 600; innery1 <- 0; innery2 <- 1600
rect(innerx1-900,innery1-100,innerx2+900,innery2+100, lwd=2, border='red')
par(fig=c(0.3,.9,.3,.9), new=T, cex=1.3)
plot(Animals, xlim=c(innerx1,600), ylim=c(innery1,1600), col='red', axes=F,
     xlab='body weight in kg', ylab='brain weight in g', col.lab='red')
axis(1, col='red', col.axis='red')
axis(2, col='red', col.axis='red')
box(col='red')
par(op)




# Animation - Evolution of density
library(animation)

n <- 15
mu <- 6
mat <- cbind(1:n, rpois(n,lambda=mu))

poisson <- function(mat) {
  oopt = ani.options(interval = 0.5, nmax = dim(mat)[1]-1)
  xlim <- c(0,max(mat[,1]))
  ## use a loop to create images one by one
  op <- par(mfrow=c(2,1))
  for (i in 1:ani.options("nmax")) {
    plot(mat[1:(i+1),], main="x", xlab="n", xlim=xlim, ylim=c(0,max(mat[,2])),
         ylab=paste("x~Poisson(mu=",mu,")",sep=""))
    plot(density(mat[1:(i+1),2]), main="Density of x", xlim=xlim, type="l", col="blue")
    ani.pause()
  }  
  par(op)
}

poisson(mat)




